name: CI

on: 
  push:
    branches:
  pull_request:
    branches:
  release:
    types: [published]
    
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: On push
      run: |
        echo Triggered by push
        
  pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: On pull-request1      
      run: |
        echo Triggered by pull_request

  release:
    runs-on: ubuntu-latest
    steps:
    - name: On release
      run: |
        echo Triggered by release
