name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!

    - name: On push
      if: github.event == 'push'
      run: |
        echo Triggered by push
        
    - name: On pull-request
      if: github.event == 'pull_request'
      run: |
        echo Triggered by pull_request
