name: CI

on: 
  push:
  pull_request:
  release:
    types: [published]
    
jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!

    - name: On push
      run: |
        echo Triggered by push
        
  pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: On pull-request      
      run: |
        echo Triggered by pull_request

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
    - name: On release
      run: |
        echo Triggered by release
